import assert from "node:assert/strict";
import {evaluateReviewGate} from "../src/go030/review-gate.mjs";
const envelope={head:"h1",base:"b1",baseBranch:"main",workflowDigest:"w1",evidenceDigest:"e1"};
const current={...envelope,requiredChecks:["PASS","PASS"]};
const review={outcome:"APPROVED",reviewerId:"human-1",reviewId:"r1",head:"h1",base:"b1",unresolvedFindings:0};
const authorization={authorized:true,actorId:"human-2",head:"h1",base:"b1"};
const check=(patch,reason)=>assert.equal(evaluateReviewGate({envelope,current,review,authorization,...patch}).reason,reason);
check({},"ELIGIBLE_FOR_SEPARATE_MERGE_EXECUTION");
check({current:{...current,base:"b2"}},"IDENTITY_DRIFT");
check({current:{...current,workflowDigest:"w2"}},"WORKFLOW_DRIFT");
check({current:{...current,evidenceDigest:"e2"}},"EVIDENCE_DRIFT");
check({current:{...current,requiredChecks:["PASS","PENDING"]}},"CHECKS_NOT_PASS");
check({review:{...review,outcome:"FINDINGS"}},"REVIEW_NOT_APPROVED");
check({review:{...review,outcome:"INCONCLUSIVE"}},"REVIEW_NOT_APPROVED");
check({review:{...review,head:"stale"}},"REVIEW_NOT_BOUND");
check({review:{...review,unresolvedFindings:1}},"UNRESOLVED_FINDINGS");
check({authorization:{...authorization,authorized:false}},"MERGE_NOT_AUTHORIZED");
check({review:null},"MISSING_EVIDENCE");
console.log("GO-030 11/11 PASS — local pure gate assertions");
