import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { createRequire } from 'node:module';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createSign, generateKeyPairSync } from 'node:crypto';
import { newCitadel, recordStep, template } from '../atelier/builder.mjs';
import { digest } from '../citadel-proof/proof.mjs';
import { LocalRegistry, grantPayload } from './registry.mjs';
import { PreviewAdapter, createDraftPackage, eraPayload } from './preview.mjs';
import { startLocalPreview } from './preview-server.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');

test('Chromium renders sandboxed srcdoc while hostile maker markup stays text',async t=>{
  const root=await mkdtemp(join(tmpdir(),'palaco-browser-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
  const sign=payload=>{const s=createSign('SHA256');s.update(payload);s.end();return s.sign(privateKey).toString('base64');};
  const now='2026-09-28T06:00:00Z',validUntil='2026-09-29T06:00:00Z';
  const registry=new LocalRegistry(root,{allowedRoot:root,clock:()=>now,trustedKeys:{issuer:publicKey}});
  const adapter=new PreviewAdapter(registry,{makerId:'maker',eraKeys:{era:publicKey}});
  let project=newCitadel({makerId:'maker',name:'<img src="https://invalid.example/leak" onerror="window.pwned=true">',intention:'Browser test',citadelId:'C1',projectId:'P1'});
  for(const step of template.required_steps) project=recordStep(project,'maker',step,'answer');
  const pkg=createDraftPackage(project,'maker'),manifestSha256=digest(pkg.manifest);
  const era={citadelId:'C1',makerId:'maker',manifestSha256,exportSequence:1,observedAt:now,validUntil,keyId:'era'};
  era.signature=sign(eraPayload(era));
  const grant={type:'AUTHORITY_GRANTED',grantId:'G1',subjectId:'maker',actorId:'issuer',citadelId:'C1',action:'PREVIEW',scope:'P1',manifestSha256,evidenceSha256:'a'.repeat(64),validUntil,issuerKeyId:'issuer'};
  grant.signature=sign(grantPayload(grant));await registry.append(grant,0);await adapter.register(pkg,era);
  const hosted=await startLocalPreview(adapter);
  t.after(()=>new Promise(resolve=>{hosted.server.closeAllConnections();hosted.server.close(resolve);}));
  const browser=await chromium.launch({headless:true});t.after(()=>browser.close());
  const page=await browser.newPage();const requests=[];page.on('request',r=>requests.push(r.url()));
  await page.goto(hosted.urlFor('C1',manifestSha256));
  const frame=page.frames().find(x=>x.parentFrame());assert.ok(frame,'sandbox frame loaded');
  assert.equal(await frame.locator('h1').textContent(),project.name);
  assert.equal(await frame.locator('img,script').count(),0);
  assert.equal(await frame.evaluate(()=>{try { parent.document.body; return false; } catch { return true; }}),true);
  assert.equal(requests.some(url=>url.includes('invalid.example')),false);
});
